name: Github Pages Deploy

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy on Github Pages
              uses: JamesIves/github-pages-deploy-action@v4
