name: Github Pages Deploy

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Deploy on Github Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build
